version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/admin"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/agent"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/content"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/governor"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/validator"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/voucher"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
