version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/content"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/geonode"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/voucher"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
