version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/example"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
