swagger: '2.0'
info:
  title: Chora Subject Module - REST and gRPC Gateway Documentation
  description: Documentation describing REST and gRPC endpoints for queries.
  version: v0.0.0
paths:
  /chora/subject/v1/subject/{address}:
    get:
      summary: Subject queries an subject by address.
      operationId: Subject
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              address:
                type: string
                description: address is the address of the subject.
              steward:
                type: string
                description: steward is the address of the subject steward.
              metadata:
                type: string
                description: metadata is the metadata of the subject.
            description: QuerySubjectResponse is the Query/Subject response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: address
          description: address is the address of the subject.
          in: path
          required: true
          type: string
      tags:
        - Query
  /chora/subject/v1/subjects:
    get:
      summary: Subjects queries all subjects.
      operationId: Subjects
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              subjects:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                      description: address is the address of the subject.
                    steward:
                      type: string
                      description: steward is the address of the subject steward.
                    metadata:
                      type: string
                      description: metadata is the metadata of the subject.
                  description: Subject is the subject properties.
                description: subjects is the list of subjects.
              pagination:
                description: pagination is the pagination of the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    description: |-
                      next_key is the key to be passed to PageRequest.key to
                      query the next page most efficiently. It will be empty if
                      there are no more results.
                  total:
                    type: string
                    format: uint64
                    title: >-
                      total is total number of results available if
                      PageRequest.count_total

                      was set, its value is undefined otherwise
            description: QuerySubjectsResponse is the Query/Subjects response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          description: >-
            reverse is set to true if results are to be returned in the
            descending order.


            Since: cosmos-sdk 0.43
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /chora/subject/v1/subjects-by-steward/{steward}:
    get:
      summary: SubjectsBySteward queries subjects by steward.
      operationId: SubjectsBySteward
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              steward:
                type: string
                description: steward is the address of the subject steward.
              subjects:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                      description: address is the address of the subject.
                    metadata:
                      type: string
                      description: metadata is the metadata of the subject.
                  description: Subject is the subject properties.
                description: subjects is the list of subjects managed by the steward.
              pagination:
                description: pagination is the pagination of the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    description: |-
                      next_key is the key to be passed to PageRequest.key to
                      query the next page most efficiently. It will be empty if
                      there are no more results.
                  total:
                    type: string
                    format: uint64
                    title: >-
                      total is total number of results available if
                      PageRequest.count_total

                      was set, its value is undefined otherwise
            description: >-
              QuerySubjectsByStewardResponse is the Query/SubjectsBySteward
              response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: steward
          description: steward is the address of the subject steward.
          in: path
          required: true
          type: string
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          description: >-
            reverse is set to true if results are to be returned in the
            descending order.


            Since: cosmos-sdk 0.43
          in: query
          required: false
          type: boolean
      tags:
        - Query
definitions:
  chora.subject.v1.QuerySubjectResponse:
    type: object
    properties:
      address:
        type: string
        description: address is the address of the subject.
      steward:
        type: string
        description: steward is the address of the subject steward.
      metadata:
        type: string
        description: metadata is the metadata of the subject.
    description: QuerySubjectResponse is the Query/Subject response type.
  chora.subject.v1.QuerySubjectsByStewardResponse:
    type: object
    properties:
      steward:
        type: string
        description: steward is the address of the subject steward.
      subjects:
        type: array
        items:
          type: object
          properties:
            address:
              type: string
              description: address is the address of the subject.
            metadata:
              type: string
              description: metadata is the metadata of the subject.
          description: Subject is the subject properties.
        description: subjects is the list of subjects managed by the steward.
      pagination:
        description: pagination is the pagination of the response.
        type: object
        properties:
          next_key:
            type: string
            format: byte
            description: |-
              next_key is the key to be passed to PageRequest.key to
              query the next page most efficiently. It will be empty if
              there are no more results.
          total:
            type: string
            format: uint64
            title: >-
              total is total number of results available if
              PageRequest.count_total

              was set, its value is undefined otherwise
    description: >-
      QuerySubjectsByStewardResponse is the Query/SubjectsBySteward response
      type.
  chora.subject.v1.QuerySubjectsByStewardResponse.Subject:
    type: object
    properties:
      address:
        type: string
        description: address is the address of the subject.
      metadata:
        type: string
        description: metadata is the metadata of the subject.
    description: Subject is the subject properties.
  chora.subject.v1.QuerySubjectsResponse:
    type: object
    properties:
      subjects:
        type: array
        items:
          type: object
          properties:
            address:
              type: string
              description: address is the address of the subject.
            steward:
              type: string
              description: steward is the address of the subject steward.
            metadata:
              type: string
              description: metadata is the metadata of the subject.
          description: Subject is the subject properties.
        description: subjects is the list of subjects.
      pagination:
        description: pagination is the pagination of the response.
        type: object
        properties:
          next_key:
            type: string
            format: byte
            description: |-
              next_key is the key to be passed to PageRequest.key to
              query the next page most efficiently. It will be empty if
              there are no more results.
          total:
            type: string
            format: uint64
            title: >-
              total is total number of results available if
              PageRequest.count_total

              was set, its value is undefined otherwise
    description: QuerySubjectsResponse is the Query/Subjects response type.
  chora.subject.v1.QuerySubjectsResponse.Subject:
    type: object
    properties:
      address:
        type: string
        description: address is the address of the subject.
      steward:
        type: string
        description: steward is the address of the subject steward.
      metadata:
        type: string
        description: metadata is the metadata of the subject.
    description: Subject is the subject properties.
  cosmos.base.query.v1beta1.PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
        description: |-
          key is a value returned in PageResponse.next_key to begin
          querying the next page most efficiently. Only one of offset or key
          should be set.
      offset:
        type: string
        format: uint64
        description: |-
          offset is a numeric offset that can be used when key is unavailable.
          It is less efficient than using key. Only one of offset or key should
          be set.
      limit:
        type: string
        format: uint64
        description: >-
          limit is the total number of results to be returned in the result
          page.

          If left empty it will default to a value to be set by each app.
      count_total:
        type: boolean
        description: >-
          count_total is set to true  to indicate that the result set should
          include

          a count of the total number of items available for pagination in UIs.

          count_total is only respected when offset is used. It is ignored when
          key

          is set.
      reverse:
        type: boolean
        description: >-
          reverse is set to true if results are to be returned in the descending
          order.


          Since: cosmos-sdk 0.43
    description: |-
      message SomeRequest {
               Foo some_parameter = 1;
               PageRequest pagination = 2;
       }
    title: |-
      PageRequest is to be embedded in gRPC request messages for efficient
      pagination. Ex:
  cosmos.base.query.v1beta1.PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
        description: |-
          next_key is the key to be passed to PageRequest.key to
          query the next page most efficiently. It will be empty if
          there are no more results.
      total:
        type: string
        format: uint64
        title: |-
          total is total number of results available if PageRequest.count_total
          was set, its value is undefined otherwise
    description: |-
      PageResponse is to be embedded in gRPC response messages where the
      corresponding request message has used PageRequest.

       message SomeResponse {
               repeated Bar results = 1;
               PageResponse page = 2;
       }
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
