swagger: '2.0'
info:
  title: Chora Geonode Module - REST and gRPC Gateway Documentation
  description: Documentation describing REST and gRPC endpoints for queries.
  version: v0.0.0
paths:
  /chora/agent/v1/agent/{address}:
    get:
      summary: Agent queries a agent by address.
      operationId: Agent
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              address:
                type: string
                description: address is the address of the agent.
              admin:
                type: string
                description: admin is the address of the agent admin.
              metadata:
                type: string
                description: metadata is the metadata of the agent.
            description: QueryAgentResponse is the Query/Agent response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: address
          description: address is the address of the agent.
          in: path
          required: true
          type: string
      tags:
        - Query
  /chora/agent/v1/agents:
    get:
      summary: Agents queries all agents.
      operationId: Agents
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              agents:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                      description: address is the address of the agent.
                    admin:
                      type: string
                      description: admin is the address of the agent admin.
                    metadata:
                      type: string
                      description: metadata is the metadata of the agent.
                  description: Agent is the agent properties.
                description: agents is the list of agents.
              pagination:
                description: pagination is the pagination of the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    description: |-
                      next_key is the key to be passed to PageRequest.key to
                      query the next page most efficiently. It will be empty if
                      there are no more results.
                  total:
                    type: string
                    format: uint64
                    title: >-
                      total is total number of results available if
                      PageRequest.count_total

                      was set, its value is undefined otherwise
            description: QueryAgentsResponse is the Query/Agents response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          description: >-
            reverse is set to true if results are to be returned in the
            descending order.


            Since: cosmos-sdk 0.43
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /chora/agent/v1/agents-by-admin/{admin}:
    get:
      summary: AgentsByAdmin queries agents by admin.
      operationId: AgentsByAdmin
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              admin:
                type: string
                description: admin is the address of the agent admin.
              agents:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                      description: address is the address of the agent.
                    metadata:
                      type: string
                      description: metadata is the metadata of the agent.
                  description: Agent is the agent properties.
                description: agents is the list of agents managed by the admin.
              pagination:
                description: pagination is the pagination of the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    description: |-
                      next_key is the key to be passed to PageRequest.key to
                      query the next page most efficiently. It will be empty if
                      there are no more results.
                  total:
                    type: string
                    format: uint64
                    title: >-
                      total is total number of results available if
                      PageRequest.count_total

                      was set, its value is undefined otherwise
            description: >-
              QueryAgentsByAdminResponse is the Query/AgentsByAdmin response
              type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: admin
          description: admin is the address of the agent admin.
          in: path
          required: true
          type: string
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          description: >-
            reverse is set to true if results are to be returned in the
            descending order.


            Since: cosmos-sdk 0.43
          in: query
          required: false
          type: boolean
      tags:
        - Query
definitions:
  chora.agent.v1.QueryAgentResponse:
    type: object
    properties:
      address:
        type: string
        description: address is the address of the agent.
      admin:
        type: string
        description: admin is the address of the agent admin.
      metadata:
        type: string
        description: metadata is the metadata of the agent.
    description: QueryAgentResponse is the Query/Agent response type.
  chora.agent.v1.QueryAgentsByAdminResponse:
    type: object
    properties:
      admin:
        type: string
        description: admin is the address of the agent admin.
      agents:
        type: array
        items:
          type: object
          properties:
            address:
              type: string
              description: address is the address of the agent.
            metadata:
              type: string
              description: metadata is the metadata of the agent.
          description: Agent is the agent properties.
        description: agents is the list of agents managed by the admin.
      pagination:
        description: pagination is the pagination of the response.
        type: object
        properties:
          next_key:
            type: string
            format: byte
            description: |-
              next_key is the key to be passed to PageRequest.key to
              query the next page most efficiently. It will be empty if
              there are no more results.
          total:
            type: string
            format: uint64
            title: >-
              total is total number of results available if
              PageRequest.count_total

              was set, its value is undefined otherwise
    description: QueryAgentsByAdminResponse is the Query/AgentsByAdmin response type.
  chora.agent.v1.QueryAgentsByAdminResponse.Agent:
    type: object
    properties:
      address:
        type: string
        description: address is the address of the agent.
      metadata:
        type: string
        description: metadata is the metadata of the agent.
    description: Agent is the agent properties.
  chora.agent.v1.QueryAgentsResponse:
    type: object
    properties:
      agents:
        type: array
        items:
          type: object
          properties:
            address:
              type: string
              description: address is the address of the agent.
            admin:
              type: string
              description: admin is the address of the agent admin.
            metadata:
              type: string
              description: metadata is the metadata of the agent.
          description: Agent is the agent properties.
        description: agents is the list of agents.
      pagination:
        description: pagination is the pagination of the response.
        type: object
        properties:
          next_key:
            type: string
            format: byte
            description: |-
              next_key is the key to be passed to PageRequest.key to
              query the next page most efficiently. It will be empty if
              there are no more results.
          total:
            type: string
            format: uint64
            title: >-
              total is total number of results available if
              PageRequest.count_total

              was set, its value is undefined otherwise
    description: QueryAgentsResponse is the Query/Agents response type.
  chora.agent.v1.QueryAgentsResponse.Agent:
    type: object
    properties:
      address:
        type: string
        description: address is the address of the agent.
      admin:
        type: string
        description: admin is the address of the agent admin.
      metadata:
        type: string
        description: metadata is the metadata of the agent.
    description: Agent is the agent properties.
  cosmos.base.query.v1beta1.PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
        description: |-
          key is a value returned in PageResponse.next_key to begin
          querying the next page most efficiently. Only one of offset or key
          should be set.
      offset:
        type: string
        format: uint64
        description: |-
          offset is a numeric offset that can be used when key is unavailable.
          It is less efficient than using key. Only one of offset or key should
          be set.
      limit:
        type: string
        format: uint64
        description: >-
          limit is the total number of results to be returned in the result
          page.

          If left empty it will default to a value to be set by each app.
      count_total:
        type: boolean
        description: >-
          count_total is set to true  to indicate that the result set should
          include

          a count of the total number of items available for pagination in UIs.

          count_total is only respected when offset is used. It is ignored when
          key

          is set.
      reverse:
        type: boolean
        description: >-
          reverse is set to true if results are to be returned in the descending
          order.


          Since: cosmos-sdk 0.43
    description: |-
      message SomeRequest {
               Foo some_parameter = 1;
               PageRequest pagination = 2;
       }
    title: |-
      PageRequest is to be embedded in gRPC request messages for efficient
      pagination. Ex:
  cosmos.base.query.v1beta1.PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
        description: |-
          next_key is the key to be passed to PageRequest.key to
          query the next page most efficiently. It will be empty if
          there are no more results.
      total:
        type: string
        format: uint64
        title: |-
          total is total number of results available if PageRequest.count_total
          was set, its value is undefined otherwise
    description: |-
      PageResponse is to be embedded in gRPC response messages where the
      corresponding request message has used PageRequest.

       message SomeResponse {
               repeated Bar results = 1;
               PageResponse page = 2;
       }
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
