swagger: '2.0'
info:
  title: Chora Validator Module - REST and gRPC Gateway Documentation
  description: Documentation describing REST and gRPC endpoints for queries.
  version: v0.0.0
paths:
  /chora/validator/v1/max-missed-blocks:
    get:
      summary: |-
        MaxMissedBlocks queries the maximum number of missed blocks before a
        validator is removed from the validator set.
      operationId: MaxMissedBlocks
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              max_missed_blocks:
                type: string
                format: int64
                description: >-
                  max_missed_blocks is the maximum number of missed blocks
                  before a validator

                  is removed from the validator set. A zero-value indicates no
                  maximum.
            description: >-
              QueryMaxMissedBlocksResponse is the Query/MaxMissedBlocks response
              type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      tags:
        - Query
  /chora/validator/v1/validator/{address}:
    get:
      summary: Validator queries a validator by address.
      operationId: Validator
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              address:
                type: string
                description: address is the address of the validator.
              metadata:
                type: string
                description: metadata is the metadata of the validator.
              missed_blocks:
                type: string
                format: int64
                description: missed_blocks is the number of missed blocks.
            description: QueryValidatorResponse is the Query/Validator response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: address
          description: address is the address of the validator.
          in: path
          required: true
          type: string
      tags:
        - Query
  /chora/validator/v1/validators:
    get:
      summary: Validators queries all validators.
      operationId: Validators
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              validators:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                      description: address is the address of the validator.
                    metadata:
                      type: string
                      description: metadata is the metadata of the validator.
                    missed_blocks:
                      type: string
                      format: int64
                      description: missed_blocks is the number of missed blocks.
                  description: Validator is the validator properties.
                description: validators is the list of validators.
              pagination:
                description: pagination is the pagination of the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    description: |-
                      next_key is the key to be passed to PageRequest.key to
                      query the next page most efficiently. It will be empty if
                      there are no more results.
                  total:
                    type: string
                    format: uint64
                    title: >-
                      total is total number of results available if
                      PageRequest.count_total

                      was set, its value is undefined otherwise
            description: QueryValidatorsResponse is the Query/Validators response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          description: >-
            reverse is set to true if results are to be returned in the
            descending order.


            Since: cosmos-sdk 0.43
          in: query
          required: false
          type: boolean
      tags:
        - Query
definitions:
  chora.validator.v1.QueryMaxMissedBlocksResponse:
    type: object
    properties:
      max_missed_blocks:
        type: string
        format: int64
        description: >-
          max_missed_blocks is the maximum number of missed blocks before a
          validator

          is removed from the validator set. A zero-value indicates no maximum.
    description: QueryMaxMissedBlocksResponse is the Query/MaxMissedBlocks response type.
  chora.validator.v1.QueryValidatorResponse:
    type: object
    properties:
      address:
        type: string
        description: address is the address of the validator.
      metadata:
        type: string
        description: metadata is the metadata of the validator.
      missed_blocks:
        type: string
        format: int64
        description: missed_blocks is the number of missed blocks.
    description: QueryValidatorResponse is the Query/Validator response type.
  chora.validator.v1.QueryValidatorsResponse:
    type: object
    properties:
      validators:
        type: array
        items:
          type: object
          properties:
            address:
              type: string
              description: address is the address of the validator.
            metadata:
              type: string
              description: metadata is the metadata of the validator.
            missed_blocks:
              type: string
              format: int64
              description: missed_blocks is the number of missed blocks.
          description: Validator is the validator properties.
        description: validators is the list of validators.
      pagination:
        description: pagination is the pagination of the response.
        type: object
        properties:
          next_key:
            type: string
            format: byte
            description: |-
              next_key is the key to be passed to PageRequest.key to
              query the next page most efficiently. It will be empty if
              there are no more results.
          total:
            type: string
            format: uint64
            title: >-
              total is total number of results available if
              PageRequest.count_total

              was set, its value is undefined otherwise
    description: QueryValidatorsResponse is the Query/Validators response type.
  chora.validator.v1.QueryValidatorsResponse.Validator:
    type: object
    properties:
      address:
        type: string
        description: address is the address of the validator.
      metadata:
        type: string
        description: metadata is the metadata of the validator.
      missed_blocks:
        type: string
        format: int64
        description: missed_blocks is the number of missed blocks.
    description: Validator is the validator properties.
  cosmos.base.query.v1beta1.PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
        description: |-
          key is a value returned in PageResponse.next_key to begin
          querying the next page most efficiently. Only one of offset or key
          should be set.
      offset:
        type: string
        format: uint64
        description: |-
          offset is a numeric offset that can be used when key is unavailable.
          It is less efficient than using key. Only one of offset or key should
          be set.
      limit:
        type: string
        format: uint64
        description: >-
          limit is the total number of results to be returned in the result
          page.

          If left empty it will default to a value to be set by each app.
      count_total:
        type: boolean
        description: >-
          count_total is set to true  to indicate that the result set should
          include

          a count of the total number of items available for pagination in UIs.

          count_total is only respected when offset is used. It is ignored when
          key

          is set.
      reverse:
        type: boolean
        description: >-
          reverse is set to true if results are to be returned in the descending
          order.


          Since: cosmos-sdk 0.43
    description: |-
      message SomeRequest {
               Foo some_parameter = 1;
               PageRequest pagination = 2;
       }
    title: |-
      PageRequest is to be embedded in gRPC request messages for efficient
      pagination. Ex:
  cosmos.base.query.v1beta1.PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
        description: |-
          next_key is the key to be passed to PageRequest.key to
          query the next page most efficiently. It will be empty if
          there are no more results.
      total:
        type: string
        format: uint64
        title: |-
          total is total number of results available if PageRequest.count_total
          was set, its value is undefined otherwise
    description: |-
      PageResponse is to be embedded in gRPC response messages where the
      corresponding request message has used PageRequest.

       message SomeResponse {
               repeated Bar results = 1;
               PageResponse page = 2;
       }
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
