swagger: '2.0'
info:
  title: Chora Authority Module - REST and gRPC Gateway Documentation
  description: Documentation describing REST and gRPC endpoints for queries.
  version: v0.0.0
paths:
  /chora/authority/v1/authority:
    get:
      summary: Authority queries the authority account.
      operationId: Authority
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              authority:
                type: string
                description: authority is the address of the authority account.
            description: QueryAuthorityResponse is the Query/Authority response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      tags:
        - Query
definitions:
  chora.authority.v1.QueryAuthorityResponse:
    type: object
    properties:
      authority:
        type: string
        description: authority is the address of the authority account.
    description: QueryAuthorityResponse is the Query/Authority response type.
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
