swagger: '2.0'
info:
  title: Chora Geonode Module - REST and gRPC Gateway Documentation
  description: Documentation describing REST and gRPC endpoints for queries.
  version: v0.0.0
paths:
  /chora/geonode/v1/node/{id}:
    get:
      summary: Node queries a node by the unique identifier of the node.
      operationId: Node
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              id:
                type: string
                format: uint64
                description: id is the unique identifier of the node.
              curator:
                type: string
                description: curator is the curator of the node.
              metadata:
                type: string
                description: metadata is the metadata of the node.
            description: QueryNodeResponse is the Query/Node response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: id
          description: id is the unique identifier of the node.
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - Query
  /chora/geonode/v1/nodes:
    get:
      summary: Nodes queries all nodes.
      operationId: Nodes
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              nodes:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                      description: id is the unique identifier of the node.
                    curator:
                      type: string
                      description: curator is the address of the node curator.
                    metadata:
                      type: string
                      description: metadata is the metadata of the node.
                  description: Node is the node properties.
                description: nodes is the list of nodes.
              pagination:
                description: pagination is the pagination of the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    description: |-
                      next_key is the key to be passed to PageRequest.key to
                      query the next page most efficiently. It will be empty if
                      there are no more results.
                  total:
                    type: string
                    format: uint64
                    title: >-
                      total is total number of results available if
                      PageRequest.count_total

                      was set, its value is undefined otherwise
            description: QueryNodesResponse is the Query/Nodes response type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          description: >-
            reverse is set to true if results are to be returned in the
            descending order.


            Since: cosmos-sdk 0.43
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /chora/geonode/v1/nodes-by-curator/{curator}:
    get:
      summary: NodesByCurator queries nodes by curator.
      operationId: NodesByCurator
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              curator:
                type: string
                description: curator is the address of the node curator.
              nodes:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                      description: id is the unique identifier of the node.
                    metadata:
                      type: string
                      description: metadata is the metadata of the node.
                  description: Node is the node properties.
                description: nodes is the list of nodes managed by the curator.
              pagination:
                description: pagination is the pagination of the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    description: |-
                      next_key is the key to be passed to PageRequest.key to
                      query the next page most efficiently. It will be empty if
                      there are no more results.
                  total:
                    type: string
                    format: uint64
                    title: >-
                      total is total number of results available if
                      PageRequest.count_total

                      was set, its value is undefined otherwise
            description: >-
              QueryNodesByCuratorResponse is the Query/NodesByCurator response
              type.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: curator
          description: curator is the address of the node curator.
          in: path
          required: true
          type: string
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          description: >-
            reverse is set to true if results are to be returned in the
            descending order.


            Since: cosmos-sdk 0.43
          in: query
          required: false
          type: boolean
      tags:
        - Query
definitions:
  chora.geonode.v1.QueryNodeResponse:
    type: object
    properties:
      id:
        type: string
        format: uint64
        description: id is the unique identifier of the node.
      curator:
        type: string
        description: curator is the curator of the node.
      metadata:
        type: string
        description: metadata is the metadata of the node.
    description: QueryNodeResponse is the Query/Node response type.
  chora.geonode.v1.QueryNodesByCuratorResponse:
    type: object
    properties:
      curator:
        type: string
        description: curator is the address of the node curator.
      nodes:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
              description: id is the unique identifier of the node.
            metadata:
              type: string
              description: metadata is the metadata of the node.
          description: Node is the node properties.
        description: nodes is the list of nodes managed by the curator.
      pagination:
        description: pagination is the pagination of the response.
        type: object
        properties:
          next_key:
            type: string
            format: byte
            description: |-
              next_key is the key to be passed to PageRequest.key to
              query the next page most efficiently. It will be empty if
              there are no more results.
          total:
            type: string
            format: uint64
            title: >-
              total is total number of results available if
              PageRequest.count_total

              was set, its value is undefined otherwise
    description: QueryNodesByCuratorResponse is the Query/NodesByCurator response type.
  chora.geonode.v1.QueryNodesByCuratorResponse.Node:
    type: object
    properties:
      id:
        type: string
        format: uint64
        description: id is the unique identifier of the node.
      metadata:
        type: string
        description: metadata is the metadata of the node.
    description: Node is the node properties.
  chora.geonode.v1.QueryNodesResponse:
    type: object
    properties:
      nodes:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
              description: id is the unique identifier of the node.
            curator:
              type: string
              description: curator is the address of the node curator.
            metadata:
              type: string
              description: metadata is the metadata of the node.
          description: Node is the node properties.
        description: nodes is the list of nodes.
      pagination:
        description: pagination is the pagination of the response.
        type: object
        properties:
          next_key:
            type: string
            format: byte
            description: |-
              next_key is the key to be passed to PageRequest.key to
              query the next page most efficiently. It will be empty if
              there are no more results.
          total:
            type: string
            format: uint64
            title: >-
              total is total number of results available if
              PageRequest.count_total

              was set, its value is undefined otherwise
    description: QueryNodesResponse is the Query/Nodes response type.
  chora.geonode.v1.QueryNodesResponse.Node:
    type: object
    properties:
      id:
        type: string
        format: uint64
        description: id is the unique identifier of the node.
      curator:
        type: string
        description: curator is the address of the node curator.
      metadata:
        type: string
        description: metadata is the metadata of the node.
    description: Node is the node properties.
  cosmos.base.query.v1beta1.PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
        description: |-
          key is a value returned in PageResponse.next_key to begin
          querying the next page most efficiently. Only one of offset or key
          should be set.
      offset:
        type: string
        format: uint64
        description: |-
          offset is a numeric offset that can be used when key is unavailable.
          It is less efficient than using key. Only one of offset or key should
          be set.
      limit:
        type: string
        format: uint64
        description: >-
          limit is the total number of results to be returned in the result
          page.

          If left empty it will default to a value to be set by each app.
      count_total:
        type: boolean
        description: >-
          count_total is set to true  to indicate that the result set should
          include

          a count of the total number of items available for pagination in UIs.

          count_total is only respected when offset is used. It is ignored when
          key

          is set.
      reverse:
        type: boolean
        description: >-
          reverse is set to true if results are to be returned in the descending
          order.


          Since: cosmos-sdk 0.43
    description: |-
      message SomeRequest {
               Foo some_parameter = 1;
               PageRequest pagination = 2;
       }
    title: |-
      PageRequest is to be embedded in gRPC request messages for efficient
      pagination. Ex:
  cosmos.base.query.v1beta1.PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
        description: |-
          next_key is the key to be passed to PageRequest.key to
          query the next page most efficiently. It will be empty if
          there are no more results.
      total:
        type: string
        format: uint64
        title: |-
          total is total number of results available if PageRequest.count_total
          was set, its value is undefined otherwise
    description: |-
      PageResponse is to be embedded in gRPC response messages where the
      corresponding request message has used PageRequest.

       message SomeResponse {
               repeated Bar results = 1;
               PageResponse page = 2;
       }
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
