name: Buf

# **What it does**: Pushes proto files to buf schema registry when
# proto files have been modified (https://buf.build/chora).
#
# **Why we have it**: Buf schema registry serves as a source of truth
# for application developers consuming the API of chora modules.
#
# **What does it impact**: Application accessibility.

on:
  push:
    branches:
      - main
    paths:
      - '**/proto/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["admin", "content", "governor", "subject", "validator", "voucher"]
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        id: git-diff-admin
        with:
          PATTERNS: |
            admin/**/**.proto
        if: matrix.module == 'admin'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-content
        with:
          PATTERNS: |
            content/**/**.proto
        if: matrix.module == 'content'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-governor
        with:
          PATTERNS: |
            governor/**/**.proto
        if: matrix.module == 'governor'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-subject
        with:
          PATTERNS: |
            subject/**/**.proto
        if: matrix.module == 'subject'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-validator
        with:
          PATTERNS: |
            validator/**/**.proto
        if: matrix.module == 'validator'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-voucher
        with:
          PATTERNS: |
            voucher/**/**.proto
        if: matrix.module == 'voucher'
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'admin/proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
        if: steps.git-diff-admin.outputs.diff
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'content/proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
        if: steps.git-diff-content.outputs.diff
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'governor/proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
        if: steps.git-diff-governor.outputs.diff
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'subject/proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
        if: steps.git-diff-subject.outputs.diff
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'validator/proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
        if: steps.git-diff-validator.outputs.diff
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'voucher/proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
        if: steps.git-diff-voucher.outputs.diff
