name: Lint

# **What it does**: Runs go linter when go files have been modified
# and proto linters when proto files have been modified.
#
# **Why we have it**: Ensures all go files and proto files are
# properly formatted according to lint configuration files.
#
# **What does it impact**: Code quality.

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["content", "geonode"]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        id: git-diff-content
        with:
          PATTERNS: |
            content/**/**.go
            content/go.mod
            content/go.sum
        if: matrix.module == 'content'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-geonode
        with:
          PATTERNS: |
            geonode/**/**.go
            geonode/go.mod
            geonode/go.sum
        if: matrix.module == 'geonode'
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'content/go.mod'
        if: steps.git-diff-content.outputs.diff
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'geonode/go.mod'
        if: steps.git-diff-geonode.outputs.diff
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: "content"
        if: steps.git-diff-content.outputs.diff
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: "geonode"
        if: steps.git-diff-geonode.outputs.diff

  buf-lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["content", "geonode"]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        id: git-diff-content
        with:
          PATTERNS: |
            content/**/**.proto
        if: matrix.module == 'content'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-geonode
        with:
          PATTERNS: |
            geonode/**/**.proto
        if: matrix.module == 'geonode'
      - uses: bufbuild/buf-setup-action@v1
        if: |
          steps.git-diff-content.outputs.diff ||
          steps.git-diff-geonode.outputs.diff
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'content/proto'
        if: steps.git-diff-content.outputs.diff
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'geonode/proto'
        if: steps.git-diff-geonode.outputs.diff

  protolint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["content", "geonode"]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        id: git-diff-content
        with:
          PATTERNS: |
            content/**/**.proto
        if: matrix.module == 'content'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-geonode
        with:
          PATTERNS: |
            geonode/**/**.proto
        if: matrix.module == 'geonode'
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'content/go.mod'
        if: steps.git-diff-content.outputs.diff
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'geonode/go.mod'
        if: steps.git-diff-geonode.outputs.diff
      - name: Install protolint
        run: go install github.com/yoheimuta/protolint/cmd/protolint@latest
        if: |
          steps.git-diff-content.outputs.diff ||
          steps.git-diff-geonode.outputs.diff
      - name: Run protolint
        run: protolint ./content
        if: steps.git-diff-content.outputs.diff
      - name: Run protolint
        run: protolint ./geonode
        if: steps.git-diff-geonode.outputs.diff
