name: Proto

# **What it does**: Checks for breaking changes in proto files
# when proto files have been modified.
#
# **Why we have it**: Provides visibility into breaking changes and
# ensures no breaking changes are merged unintentionally.
#
# **What does it impact**: Application release process.

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/proto/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  break-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["admin", "agent", "content", "governor", "validator", "voucher"]
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        id: git-diff-admin
        with:
          PATTERNS: |
            admin/**/**.go
            admin/go.mod
            admin/go.sum
        if: matrix.module == 'admin'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-agent
        with:
          PATTERNS: |
            agent/**/**.go
            agent/go.mod
            agent/go.sum
        if: matrix.module == 'agent'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-content
        with:
          PATTERNS: |
            content/**/**.go
            content/go.mod
            content/go.sum
        if: matrix.module == 'content'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-governor
        with:
          PATTERNS: |
            governor/**/**.go
            governor/go.mod
            governor/go.sum
        if: matrix.module == 'governor'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-validator
        with:
          PATTERNS: |
            validator/**/**.go
            validator/go.mod
            validator/go.sum
        if: matrix.module == 'validator'
      - uses: technote-space/get-diff-action@v6
        id: git-diff-voucher
        with:
          PATTERNS: |
            voucher/**/**.go
            voucher/go.mod
            voucher/go.sum
        if: matrix.module == 'voucher'
      - uses: bufbuild/buf-setup-action@v1
        if: |
          steps.git-diff-admin.outputs.diff ||
          steps.git-diff-agent.outputs.diff ||
          steps.git-diff-content.outputs.diff ||
          steps.git-diff-governor.outputs.diff ||
          steps.git-diff-validator.outputs.diff ||
          steps.git-diff-voucher.outputs.diff
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'admin/proto'
          against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=admin/proto'
        if: steps.git-diff-content.outputs.diff
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'agent/proto'
          against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=agent/proto'
        if: steps.git-diff-agent.outputs.diff
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'content/proto'
          against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=content/proto'
        if: steps.git-diff-content.outputs.diff
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'governor/proto'
          against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=governor/proto'
        if: steps.git-diff-agent.outputs.diff
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'validator/proto'
          against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=validator/proto'
        if: steps.git-diff-validator.outputs.diff
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'voucher/proto'
          against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=voucher/proto'
        if: steps.git-diff-voucher.outputs.diff
