name: Test

# **What it does**: Runs unit and integration tests when go files
# have been modified and provides code coverage reports.
#
# **Why we have it**: Ensures the application is production ready.
#
# **What does it impact**: Application stability.

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    strategy:
      matrix:
        module: ["content"]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'content/go.mod'
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-content
        if: |
          (env.GIT_DIFF && matrix.module == 'content') ||
          github.ref == 'refs/heads/main'
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-content
          path: content/coverage-content.out
        if: |
          (env.GIT_DIFF && matrix.module == 'content') ||
          github.ref == 'refs/heads/main'

  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # for technote-space/get-diff-action to get git reference
    needs: [unit]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            **/go.mod
            **/go.sum
      - uses: actions/download-artifact@v3
        with:
          name: coverage-content
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - run: make test-coverage
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
      - uses: codecov/codecov-action@v3
        with:
          file: coverage.txt
        if: env.GIT_DIFF || github.ref == 'refs/heads/main'
